tclmode

# Generated by Genus(TM) Synthesis Solution 17.22-s017_1, revision 1.272a
# Generated on: Thu Nov 23 10:25:51 IST 2023 (Thu Nov 23 04:55:51 GMT 2023)

set lec_version [regsub {(-).} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file fv/dtmf_recvr_core/rtl_to_fv_map.log -replace

usage -auto -elapse

set_verification_information rtl_fv_map_db

read_implementation_information fv/dtmf_recvr_core -revised fv_map

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.22-s017_1"
set env(CDN_SYNTH_ROOT) "/home/install/GENUS172/tools.lnx86"
set CDN_SYNTH_ROOT      "/home/install/GENUS172/tools.lnx86"
set env(CW_DIR) "/home/install/GENUS172/tools.lnx86/lib/chipware"
set CW_DIR      "/home/install/GENUS172/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_notranslate_modules -library -both ram_256x16A rom_512x16A pllclk

add_search_path /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/STDCELL /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/IO /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/LEF/STDCELL /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/LEF/CUSTOM /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/LEF/IO -library -both
read_library -liberty -both   /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/STDCELL/ss_g_1v08_125c.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/STDCELL/ss_hvt_1v08_125c.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/ram_256x16A_slow_syn.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/rom_512x16A_slow_syn.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/pllclk_slow.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/STDCELL/ss_g_1v08_125c.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/STDCELL/ss_hvt_1v08_125c.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/ram_256x16A_slow_syn.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/rom_512x16A_slow_syn.lib /home/kamalesh/Desktop/VDI/genus_labs/work/../libraries/TIMING/CUSTOM/pllclk_slow.lib

set_undriven_signal Z -golden
set_naming_style rc -golden
set_naming_rule "%s\[%d\]" -instance_array -golden
set_naming_rule "%s_reg" -register -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -instance -golden
set_naming_rule "%L.%s" "%L\[%d\].%s" "%s" -variable -golden

# Align LEC's treatment of mismatched port widths with constant
# connections with Genus's. Genus message CDFG-467 and LEC message
# HRC3.6 may indicate the presence of this issue. This option is
# only available with LEC 17.20-d301 or later.
set lec_version_required "17.20301"
if {$lec_version >= $lec_version_required} {
    set_hdl_options -const_port_extend
}
set_hdl_options -VERILOG_INCLUDE_DIR "incdir:sep:src:cwd"

delete_search_path -all -design -golden
add_search_path /home/kamalesh/Desktop/VDI/genus_labs/work/../rtl -design -golden
read_design   -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -verilog2k /home/kamalesh/Desktop/VDI/genus_labs/rtl/alu_32.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/arb.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/data_bus_mach.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/data_sample_mux.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/decode_i.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/digit_reg.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/conv_subreg.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/dma.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/dtmf_recvr_core.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/execute_i.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/m16x16.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/mult_32_dp.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/port_bus_mach.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/prog_bus_mach.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/ram_128x16_test.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/ram_256x16_test.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/results_conv.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/spi.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/tdsp_core_glue.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/tdsp_core_mach.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/tdsp_core.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/tdsp_data_mux.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/tdsp_ds_cs.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/test_control.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/ulaw_lin_conv.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/power_manager.v /home/kamalesh/Desktop/VDI/genus_labs/rtl/accum_stat.v
elaborate_design -golden -root {dtmf_recvr_core} -rootonly 

read_design -verilog95   -revised -lastmod -noelab fv/dtmf_recvr_core/fv_map.v.gz
elaborate_design -revised -root {dtmf_recvr_core}

uniquify -all -nolib -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/dtmf_recvr_core/fv_map.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

write_hier_compare_dofile hier_tmp1.lec.do -noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence -prepend_string " analyze_datapath -module -verbose ; analyze_datapath -share  -verbose; "
run_hier_compare hier_tmp1.lec.do -dynamic_hierarchy

report_verification -hier -verbose
set_system_mode lec
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}

write_verification_information
report_verification_information

exit

